name: TecHooT
title: TecHooT
description: The Techoot (or TecH007) is a blog about computers mainly targeted at those with little to no prior technical knowledge.
tags:
  - blog
  - computer systems
  - security
  - graphics
  - cpu
  - processor
  - gpu
  - computer
  - hardware
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: 
disqus_username: disqus_aznAsbGyyK
